// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hafta_8_emlak_b.Models;

#nullable disable

namespace hafta_8_emlak_b.Migrations
{
    [DbContext(typeof(hafta_8_emlak_b.Models.AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.BaglantiTip", b =>
                {
                    b.Property<int>("baglantiTipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("baglantiTipId"));

                    b.Property<string>("baglatiTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("baglantiTipId");

                    b.ToTable("BaglantiTipler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Batarya", b =>
                {
                    b.Property<int>("bataryaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bataryaId"));

                    b.Property<int>("bataryaMiktarı")
                        .HasColumnType("int");

                    b.HasKey("bataryaId");

                    b.ToTable("Bataryalar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Bluetooth", b =>
                {
                    b.Property<int>("btId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("btId"));

                    b.Property<bool>("btVar")
                        .HasColumnType("bit");

                    b.HasKey("btId");

                    b.ToTable("Bluetoothlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.BtStandart", b =>
                {
                    b.Property<int>("btStandartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("btStandartId"));

                    b.Property<float>("btStandart")
                        .HasColumnType("real");

                    b.HasKey("btStandartId");

                    b.ToTable("BtStandartlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Compability5G", b =>
                {
                    b.Property<int>("comp5GId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("comp5GId"));

                    b.Property<bool>("comp5GVar")
                        .HasColumnType("bit");

                    b.HasKey("comp5GId");

                    b.ToTable("Compability5Gler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.CpuHz", b =>
                {
                    b.Property<int>("cpuHzId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cpuHzId"));

                    b.Property<float>("cpuHz")
                        .HasColumnType("real");

                    b.HasKey("cpuHzId");

                    b.ToTable("CpuHzler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Depolama", b =>
                {
                    b.Property<int>("depolamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("depolamaId"));

                    b.Property<string>("depolamaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("depolamaId");

                    b.ToTable("Depolamalar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.EkranCoz", b =>
                {
                    b.Property<int>("ekranCozId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ekranCozId"));

                    b.Property<int>("ekranCozDikey")
                        .HasColumnType("int");

                    b.Property<int>("ekranCozYatay")
                        .HasColumnType("int");

                    b.HasKey("ekranCozId");

                    b.ToTable("EkranCozler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Hat", b =>
                {
                    b.Property<int>("hatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hatId"));

                    b.Property<string>("hatTur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hatId");

                    b.ToTable("Hatlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.HizliSarj", b =>
                {
                    b.Property<int>("hSarjId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hSarjId"));

                    b.Property<bool>("hSarjVar")
                        .HasColumnType("bit");

                    b.HasKey("hSarjId");

                    b.ToTable("HizliSarjlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.KameraCoz", b =>
                {
                    b.Property<int>("kameraCozId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kameraCozId"));

                    b.Property<int>("kameraCoz")
                        .HasColumnType("int");

                    b.HasKey("kameraCozId");

                    b.ToTable("KameraCozler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Kulaklik", b =>
                {
                    b.Property<int>("kulaklikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kulaklikId"));

                    b.Property<int>("baglantiTipId")
                        .HasColumnType("int");

                    b.Property<int>("btId")
                        .HasColumnType("int");

                    b.Property<int>("btStandartId")
                        .HasColumnType("int");

                    b.Property<float>("fiyat")
                        .HasColumnType("real");

                    b.Property<string>("kulaklikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mikrofonId")
                        .HasColumnType("int");

                    b.Property<int>("sesCikisId")
                        .HasColumnType("int");

                    b.HasKey("kulaklikId");

                    b.HasIndex("baglantiTipId");

                    b.HasIndex("btId");

                    b.HasIndex("btStandartId");

                    b.HasIndex("mikrofonId");

                    b.HasIndex("sesCikisId");

                    b.ToTable("Kulakliklar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Mikrofon", b =>
                {
                    b.Property<int>("mikrofonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mikrofonId"));

                    b.Property<bool>("mikrofonVar")
                        .HasColumnType("bit");

                    b.HasKey("mikrofonId");

                    b.ToTable("Mikrofonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.ParmakIzi", b =>
                {
                    b.Property<int>("parmakIziId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("parmakIziId"));

                    b.Property<bool>("parmakIziVar")
                        .HasColumnType("bit");

                    b.HasKey("parmakIziId");

                    b.ToTable("ParmakIzler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Ram", b =>
                {
                    b.Property<int>("ramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ramId"));

                    b.Property<int>("ramMiktari")
                        .HasColumnType("int");

                    b.HasKey("ramId");

                    b.ToTable("Ramler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.SesCikis", b =>
                {
                    b.Property<int>("sesCikisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sesCikisId"));

                    b.Property<string>("sesCikisTur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sesCikisId");

                    b.ToTable("SesCikislar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Su", b =>
                {
                    b.Property<int>("suDayanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("suDayanId"));

                    b.Property<bool>("suDayananikli")
                        .HasColumnType("bit");

                    b.HasKey("suDayanId");

                    b.ToTable("Sular");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.SuSertifika", b =>
                {
                    b.Property<int>("suSertifikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("suSertifikaId"));

                    b.Property<string>("suSertifikaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("suSertifikaId");

                    b.ToTable("SuSertifikalar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.TelMarka", b =>
                {
                    b.Property<int>("telMarkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("telMarkaId"));

                    b.Property<string>("telMarkaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("telMarkaId");

                    b.ToTable("TelMarkalar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Telefon", b =>
                {
                    b.Property<int>("telId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("telId"));

                    b.Property<int>("bataryaId")
                        .HasColumnType("int");

                    b.Property<int>("comp5GId")
                        .HasColumnType("int");

                    b.Property<int>("cpuHzId")
                        .HasColumnType("int");

                    b.Property<int>("depolamaId")
                        .HasColumnType("int");

                    b.Property<int>("ekranCozId")
                        .HasColumnType("int");

                    b.Property<float>("fiyat")
                        .HasColumnType("real");

                    b.Property<int>("hSarjId")
                        .HasColumnType("int");

                    b.Property<int>("hatId")
                        .HasColumnType("int");

                    b.Property<int>("kameraCozId")
                        .HasColumnType("int");

                    b.Property<int>("parmakIziId")
                        .HasColumnType("int");

                    b.Property<int>("ramId")
                        .HasColumnType("int");

                    b.Property<int>("suDayanId")
                        .HasColumnType("int");

                    b.Property<int>("suSertifikaId")
                        .HasColumnType("int");

                    b.Property<string>("telAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("telMarkaId")
                        .HasColumnType("int");

                    b.HasKey("telId");

                    b.HasIndex("bataryaId");

                    b.HasIndex("comp5GId");

                    b.HasIndex("cpuHzId");

                    b.HasIndex("depolamaId");

                    b.HasIndex("ekranCozId");

                    b.HasIndex("hSarjId");

                    b.HasIndex("hatId");

                    b.HasIndex("kameraCozId");

                    b.HasIndex("parmakIziId");

                    b.HasIndex("ramId");

                    b.HasIndex("suDayanId");

                    b.HasIndex("suSertifikaId");

                    b.HasIndex("telMarkaId");

                    b.ToTable("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Emlak.Emlak", b =>
                {
                    b.Property<int>("EmlakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmlakId"));

                    b.Property<string>("EmlakAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KatId")
                        .HasColumnType("int");

                    b.Property<int>("ilceId")
                        .HasColumnType("int");

                    b.HasKey("EmlakId");

                    b.HasIndex("KatId");

                    b.HasIndex("ilceId");

                    b.ToTable("Emlaklar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Emlak.Kategori", b =>
                {
                    b.Property<int>("KatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KatId"));

                    b.Property<string>("KatAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KatId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.IkinciEl.IkinciEl", b =>
                {
                    b.Property<int>("urunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("urunId"));

                    b.Property<int>("durumId")
                        .HasColumnType("int");

                    b.Property<int>("ilceId")
                        .HasColumnType("int");

                    b.Property<int>("ukId")
                        .HasColumnType("int");

                    b.Property<string>("urunBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("urunFiyat")
                        .HasColumnType("int");

                    b.HasKey("urunId");

                    b.HasIndex("durumId");

                    b.HasIndex("ilceId");

                    b.HasIndex("ukId");

                    b.ToTable("IkinciEller");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.IkinciEl.UrunDurum", b =>
                {
                    b.Property<int>("durumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("durumId"));

                    b.Property<string>("durumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("durumId");

                    b.ToTable("UrunDurumlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.IkinciEl.UrunKategori", b =>
                {
                    b.Property<int>("ukId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ukId"));

                    b.Property<string>("ukAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ukId");

                    b.ToTable("UrunKategoriler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Ilce", b =>
                {
                    b.Property<int>("ilceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ilceId"));

                    b.Property<int>("Plaka")
                        .HasColumnType("int");

                    b.Property<string>("ilceAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ilceId");

                    b.HasIndex("Plaka");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Kurs.Kurs", b =>
                {
                    b.Property<int>("kursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kursId"));

                    b.Property<decimal>("fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ilceId")
                        .HasColumnType("int");

                    b.Property<string>("kursAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sinifId")
                        .HasColumnType("int");

                    b.HasKey("kursId");

                    b.HasIndex("ilceId");

                    b.HasIndex("sinifId");

                    b.ToTable("Kurslar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Kurs.Siniflar", b =>
                {
                    b.Property<int>("sinifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sinifId"));

                    b.Property<string>("sinifAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sinifId");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Otomotiv.Marka", b =>
                {
                    b.Property<int>("markaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("markaId"));

                    b.Property<string>("markaAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("markaId");

                    b.ToTable("Markalar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Otomotiv.Otomotiv", b =>
                {
                    b.Property<int>("otoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("otoId"));

                    b.Property<int>("ilceId")
                        .HasColumnType("int");

                    b.Property<int>("markaId")
                        .HasColumnType("int");

                    b.Property<string>("otoAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("otoFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("otoKm")
                        .HasColumnType("int");

                    b.Property<string>("otoRenk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("otoYil")
                        .HasColumnType("int");

                    b.Property<int>("vitesId")
                        .HasColumnType("int");

                    b.Property<int>("yakitId")
                        .HasColumnType("int");

                    b.HasKey("otoId");

                    b.HasIndex("ilceId");

                    b.HasIndex("markaId");

                    b.HasIndex("vitesId");

                    b.HasIndex("yakitId");

                    b.ToTable("Otomotivler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Otomotiv.Vites", b =>
                {
                    b.Property<int>("vitesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vitesId"));

                    b.Property<string>("vitesAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vitesId");

                    b.ToTable("Vitesler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Otomotiv.Yakit", b =>
                {
                    b.Property<int>("yakitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("yakitId"));

                    b.Property<string>("yakitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("yakitId");

                    b.ToTable("Yakitlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Sehir", b =>
                {
                    b.Property<int>("Plaka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Plaka"));

                    b.Property<string>("SehirAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Plaka");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.SporSalonu.Aktivite", b =>
                {
                    b.Property<int>("aktiviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("aktiviteId"));

                    b.Property<string>("aktiviteAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("aktiviteId");

                    b.ToTable("Aktiviteler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.SporSalonu.Olanak", b =>
                {
                    b.Property<int>("olanakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("olanakId"));

                    b.Property<string>("olanakAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("olanakId");

                    b.ToTable("Olanaklar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.SporSalonu.SporSalonu", b =>
                {
                    b.Property<int>("salonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("salonId"));

                    b.Property<int>("aktiviteId")
                        .HasColumnType("int");

                    b.Property<decimal>("fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ilceId")
                        .HasColumnType("int");

                    b.Property<int>("olanakId")
                        .HasColumnType("int");

                    b.Property<string>("salonAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("uyelikId")
                        .HasColumnType("int");

                    b.HasKey("salonId");

                    b.HasIndex("aktiviteId");

                    b.HasIndex("ilceId");

                    b.HasIndex("olanakId");

                    b.HasIndex("uyelikId");

                    b.ToTable("SporSalonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.SporSalonu.UyelikTip", b =>
                {
                    b.Property<int>("uyelikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uyelikId"));

                    b.Property<string>("uyelikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("uyelikId");

                    b.ToTable("UyelikTipler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Kulaklik", b =>
                {
                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.BaglantiTip", "BaglantiTip")
                        .WithMany("Kulakliklar")
                        .HasForeignKey("baglantiTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.Bluetooth", "Bluetooth")
                        .WithMany("Kulakliklar")
                        .HasForeignKey("btId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.BtStandart", "BtStandart")
                        .WithMany("Kulakliklar")
                        .HasForeignKey("btStandartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.Mikrofon", "Mikrofon")
                        .WithMany("Kulakliklar")
                        .HasForeignKey("mikrofonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.SesCikis", "SesCikis")
                        .WithMany("Kulakliklar")
                        .HasForeignKey("sesCikisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaglantiTip");

                    b.Navigation("Bluetooth");

                    b.Navigation("BtStandart");

                    b.Navigation("Mikrofon");

                    b.Navigation("SesCikis");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Telefon", b =>
                {
                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.Batarya", "Batarya")
                        .WithMany("Telefonlar")
                        .HasForeignKey("bataryaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.Compability5G", "Compability5G")
                        .WithMany("Telefonlar")
                        .HasForeignKey("comp5GId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.CpuHz", "CpuHz")
                        .WithMany("Telefonlar")
                        .HasForeignKey("cpuHzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.Depolama", "Depolama")
                        .WithMany("Telefonlar")
                        .HasForeignKey("depolamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.EkranCoz", "EkranCoz")
                        .WithMany("Telefonlar")
                        .HasForeignKey("ekranCozId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.HizliSarj", "HizliSarj")
                        .WithMany("Telefonlar")
                        .HasForeignKey("hSarjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.Hat", "Hat")
                        .WithMany("Telefonlar")
                        .HasForeignKey("hatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.KameraCoz", "KameraCoz")
                        .WithMany("Telefonlar")
                        .HasForeignKey("kameraCozId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.ParmakIzi", "ParmakIzi")
                        .WithMany("Telefonlar")
                        .HasForeignKey("parmakIziId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.Ram", "Ram")
                        .WithMany("Telefonlar")
                        .HasForeignKey("ramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.Su", "Su")
                        .WithMany("Telefonlar")
                        .HasForeignKey("suDayanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.SuSertifika", "SuSertifika")
                        .WithMany("Telefonlar")
                        .HasForeignKey("suSertifikaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Elektronik.TelMarka", "TelMarka")
                        .WithMany("Telefonlar")
                        .HasForeignKey("telMarkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batarya");

                    b.Navigation("Compability5G");

                    b.Navigation("CpuHz");

                    b.Navigation("Depolama");

                    b.Navigation("EkranCoz");

                    b.Navigation("Hat");

                    b.Navigation("HizliSarj");

                    b.Navigation("KameraCoz");

                    b.Navigation("ParmakIzi");

                    b.Navigation("Ram");

                    b.Navigation("Su");

                    b.Navigation("SuSertifika");

                    b.Navigation("TelMarka");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Emlak.Emlak", b =>
                {
                    b.HasOne("hafta_8_emlak_b.Models.Emlak.Kategori", "Kategori")
                        .WithMany("Emlaklar")
                        .HasForeignKey("KatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Ilce", "Ilce")
                        .WithMany("Emlaklar")
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.IkinciEl.IkinciEl", b =>
                {
                    b.HasOne("hafta_8_emlak_b.Models.IkinciEl.UrunDurum", "UrunDurum")
                        .WithMany("IkinciEller")
                        .HasForeignKey("durumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Ilce", "Ilce")
                        .WithMany("IkinciEller")
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.IkinciEl.UrunKategori", "UrunKategori")
                        .WithMany("IkinciEller")
                        .HasForeignKey("ukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");

                    b.Navigation("UrunDurum");

                    b.Navigation("UrunKategori");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Ilce", b =>
                {
                    b.HasOne("hafta_8_emlak_b.Models.Sehir", "Sehir")
                        .WithMany("Ilceler")
                        .HasForeignKey("Plaka")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Kurs.Kurs", b =>
                {
                    b.HasOne("hafta_8_emlak_b.Models.Ilce", "Ilce")
                        .WithMany("Kurslar")
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Kurs.Siniflar", "Siniflar")
                        .WithMany("Kurslar")
                        .HasForeignKey("sinifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");

                    b.Navigation("Siniflar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Otomotiv.Otomotiv", b =>
                {
                    b.HasOne("hafta_8_emlak_b.Models.Ilce", "Ilce")
                        .WithMany("Otomotivler")
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Otomotiv.Marka", "Marka")
                        .WithMany("Otomotivler")
                        .HasForeignKey("markaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Otomotiv.Vites", "Vites")
                        .WithMany("Otomotivler")
                        .HasForeignKey("vitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Otomotiv.Yakit", "Yakit")
                        .WithMany("Otomotivler")
                        .HasForeignKey("yakitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");

                    b.Navigation("Marka");

                    b.Navigation("Vites");

                    b.Navigation("Yakit");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.SporSalonu.SporSalonu", b =>
                {
                    b.HasOne("hafta_8_emlak_b.Models.SporSalonu.Aktivite", "Aktivite")
                        .WithMany("SporSalonlar")
                        .HasForeignKey("aktiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.Ilce", "Ilce")
                        .WithMany("SporSalonlar")
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.SporSalonu.Olanak", "Olanak")
                        .WithMany("SporSalonlar")
                        .HasForeignKey("olanakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hafta_8_emlak_b.Models.SporSalonu.UyelikTip", "UyelikTip")
                        .WithMany("SporSalonlar")
                        .HasForeignKey("uyelikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktivite");

                    b.Navigation("Ilce");

                    b.Navigation("Olanak");

                    b.Navigation("UyelikTip");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.BaglantiTip", b =>
                {
                    b.Navigation("Kulakliklar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Batarya", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Bluetooth", b =>
                {
                    b.Navigation("Kulakliklar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.BtStandart", b =>
                {
                    b.Navigation("Kulakliklar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Compability5G", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.CpuHz", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Depolama", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.EkranCoz", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Hat", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.HizliSarj", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.KameraCoz", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Mikrofon", b =>
                {
                    b.Navigation("Kulakliklar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.ParmakIzi", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Ram", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.SesCikis", b =>
                {
                    b.Navigation("Kulakliklar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.Su", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.SuSertifika", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Elektronik.TelMarka", b =>
                {
                    b.Navigation("Telefonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Emlak.Kategori", b =>
                {
                    b.Navigation("Emlaklar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.IkinciEl.UrunDurum", b =>
                {
                    b.Navigation("IkinciEller");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.IkinciEl.UrunKategori", b =>
                {
                    b.Navigation("IkinciEller");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Ilce", b =>
                {
                    b.Navigation("Emlaklar");

                    b.Navigation("IkinciEller");

                    b.Navigation("Kurslar");

                    b.Navigation("Otomotivler");

                    b.Navigation("SporSalonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Kurs.Siniflar", b =>
                {
                    b.Navigation("Kurslar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Otomotiv.Marka", b =>
                {
                    b.Navigation("Otomotivler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Otomotiv.Vites", b =>
                {
                    b.Navigation("Otomotivler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Otomotiv.Yakit", b =>
                {
                    b.Navigation("Otomotivler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.Sehir", b =>
                {
                    b.Navigation("Ilceler");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.SporSalonu.Aktivite", b =>
                {
                    b.Navigation("SporSalonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.SporSalonu.Olanak", b =>
                {
                    b.Navigation("SporSalonlar");
                });

            modelBuilder.Entity("hafta_8_emlak_b.Models.SporSalonu.UyelikTip", b =>
                {
                    b.Navigation("SporSalonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
